#!/usr/bin/env bash
# install-agent.sh — Install and enroll the hp-agent on a managed host.
#
# Usage (flags, as generated by the HomePilot UI):
#   curl -fsSL .../install-agent.sh | bash -s -- --hub HOST:PORT --token TOKEN
#
# Or with env vars:
#   HUB=HOST:PORT TOKEN=... curl -fsSL .../install-agent.sh | bash
#
# Options:
#   --hub HOST:PORT   Agent Hub address (host and port). Required to enroll.
#   --token TOKEN     Hub auth token or one-time bootstrap token. Required to enroll.
#   --version TAG     Release tag (e.g. v2.3.7). Default: latest.
#   --tls             Connect to the hub over TLS.
#   --privileged      Allow privileged commands (default: safe allowlist only).
#   --no-start        Install the unit but do not start it.
#
# The agent is purely env-configured and runs as a systemd service. This script
# writes /etc/homepilot/agent.env with the connection settings and installs the
# hp-agent.service unit pointing at it.

set -euo pipefail

REPO="mtclab/homepilot-core-public"
VERSION="${VERSION:-latest}"
INSTALL_DIR="${INSTALL_DIR:-/usr/local/bin}"
HUB="${HUB:-}"
TOKEN="${TOKEN:-}"
USE_TLS="${USE_TLS:-false}"
PRIVILEGED="${PRIVILEGED:-false}"
START=1

# ─── Parse flags (the UI passes --hub / --token) ───
while [ $# -gt 0 ]; do
    case "$1" in
        --hub)        HUB="$2"; shift 2 ;;
        --token)      TOKEN="$2"; shift 2 ;;
        --version)    VERSION="$2"; shift 2 ;;
        --tls)        USE_TLS="true"; shift ;;
        --privileged) PRIVILEGED="true"; shift ;;
        --no-start)   START=0; shift ;;
        *) echo "Unknown option: $1" >&2; exit 1 ;;
    esac
done

# Strip an accidental scheme and split HOST:PORT.
HUB="${HUB#http://}"; HUB="${HUB#https://}"
HUB_HOST="${HUB%%:*}"
HUB_PORT="${HUB##*:}"
[ "$HUB_PORT" = "$HUB" ] && HUB_PORT="8443"  # no port given → default

SUDO=""
[ "$(id -u)" -ne 0 ] && SUDO="sudo"

# ─── Detect arch ───
ARCH=$(uname -m)
case "$ARCH" in
    x86_64)  GOARCH="amd64" ;;
    aarch64|arm64) GOARCH="arm64" ;;
    *) echo "Unsupported architecture: $ARCH" >&2; exit 1 ;;
esac

echo "=== Installing hp-agent (linux-$GOARCH) ==="

# ─── Resolve version ───
if [ "$VERSION" = "latest" ]; then
    VERSION=$(curl -sL "https://api.github.com/repos/$REPO/releases/latest" \
        | grep '"tag_name":' | head -1 | sed 's/.*"tag_name": "\([^"]*\)".*/\1/')
    [ -z "$VERSION" ] && { echo "Could not resolve latest release tag." >&2; exit 1; }
    echo "Latest release: $VERSION"
fi

# ─── Download ───
URL="https://github.com/$REPO/releases/download/$VERSION/hp-agent-linux-$GOARCH"
echo "Downloading $URL ..."
curl -fSL -o /tmp/hp-agent "$URL"
if ! file /tmp/hp-agent | grep -q "ELF"; then
    echo "Downloaded file is not a valid binary. Check the release exists." >&2
    exit 1
fi
chmod +x /tmp/hp-agent
$SUDO mv /tmp/hp-agent "$INSTALL_DIR/hp-agent"
echo "Installed to $INSTALL_DIR/hp-agent"

# ─── Create the service user (no login, no home writes needed) ───
if ! id hp-agent >/dev/null 2>&1; then
    $SUDO useradd --system --no-create-home --shell /usr/sbin/nologin hp-agent 2>/dev/null \
        || $SUDO adduser --system --no-create-home --shell /usr/sbin/nologin hp-agent 2>/dev/null \
        || true
fi

if [ -z "$HUB_HOST" ] || [ -z "$TOKEN" ]; then
    echo ""
    echo "Binary installed. To enroll, re-run with: --hub HOST:PORT --token TOKEN"
    exit 0
fi

# ─── Write the agent environment file ───
echo "=== Configuring agent → hub $HUB_HOST:$HUB_PORT ==="
$SUDO mkdir -p /etc/homepilot
$SUDO tee /etc/homepilot/agent.env >/dev/null <<EOF
HP_AGENT_HUB_HOST=$HUB_HOST
HP_AGENT_HUB_PORT=$HUB_PORT
HP_AGENT_AUTH_TOKEN=$TOKEN
HP_AGENT_TLS=$USE_TLS
HP_AGENT_PRIVILEGED=$PRIVILEGED
HP_AGENT_LOG_LEVEL=INFO
EOF
$SUDO chmod 600 /etc/homepilot/agent.env
$SUDO chown hp-agent:hp-agent /etc/homepilot/agent.env 2>/dev/null || true

# ─── Install the systemd unit ───
$SUDO tee /etc/systemd/system/hp-agent.service >/dev/null <<'EOF'
[Unit]
Description=HomePilot Agent
After=network-online.target
Wants=network-online.target
StartLimitBurst=3
StartLimitIntervalSec=60

[Service]
Type=simple
User=hp-agent
Group=hp-agent
EnvironmentFile=/etc/homepilot/agent.env
ExecStart=/usr/local/bin/hp-agent
Restart=always
RestartSec=5
NoNewPrivileges=yes
ProtectSystem=strict
ProtectHome=yes
PrivateTmp=yes

[Install]
WantedBy=multi-user.target
EOF

$SUDO systemctl daemon-reload
$SUDO systemctl enable hp-agent >/dev/null 2>&1 || true
if [ "$START" -eq 1 ]; then
    $SUDO systemctl restart hp-agent
    sleep 2
    if $SUDO systemctl is-active --quiet hp-agent; then
        echo "hp-agent is running and connecting to $HUB_HOST:$HUB_PORT."
        echo "Check the Agents page in HomePilot — this host should appear shortly."
    else
        echo "hp-agent failed to start. Logs:" >&2
        $SUDO journalctl -u hp-agent --no-pager -n 20 >&2 || true
        exit 1
    fi
else
    echo "Installed (not started). Start with: $SUDO systemctl start hp-agent"
fi
